### ISSUE TITLE
Don't think the readthedocs_setup hack is needed any more?

### ISSUE THREAD

**Issue by ghost** [OpenDataServices/sphinx-base#2]
The readthedocs_setup hack is used to run 2 pip install processes, the first to upgrade pip/setuptools and the second to install the full requirements.

I don't think this is needed any more.

See https://github.com/openownership/data-standard/tree/60-refactor-docs ( 60-refactor-docs is the current working branch, it will hopefully be merged to master later.)

**Comment by Bjwebb** [comment]
Yes, have removed.

**Comment by ghost** [comment]
So should the 	pre_requirements.txt be removed to?

Also the readme needs updating? It still mentions "Requirements file: readthedocs_requirements.txt"

**Comment by Bjwebb** [comment]
Yes. This should be actually sorted now.
