### ISSUE TITLE
Use MyST instead of Recommonmark

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/sphinx-base#6]
From https://github.com/readthedocs/recommonmark:

> **Warning:** recommonmark is now deprecated. We recommend using [MyST](https://github.com/executablebooks/MyST-Parser) for a docutils bridge going forward. See [this issue](https://github.com/readthedocs/recommonmark/issues/221) for background and discussion.

**Comment by ScatteredInk** [comment]
I think this was already implemented in https://github.com/OpenDataServices/sphinx-base/pull/5

But the readme was not updated and there is no changelog, so it is not possible to tell this without inspecting https://github.com/OpenDataServices/sphinx-base/blob/8e4924fa58e2c0224e44f7fda4ff62078700538d/docs/conf.py#L33

I have had a similar issue in the past using this template and being unsure about the extensions that were added in https://github.com/OpenDataServices/sphinx-base/issues/1

Therefore I think we just need to update the readme to say what this repo actually does, including being explicit about the inclusion of ODSC maintained extensions.

**Comment by duncandewhurst** [comment]
Sounds good. Thanks, @ScatteredInk!
